---
name: coverage

on:
  push:
    branches: [master]

jobs:
  coverage-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Install dependencies
        run: |
          go mod vendor
      - name: Run tests
        run: |
          go test -v -covermode=count -coverprofile=coverage.out ./...
      - name: Convert Go coverage to LCOV
        uses: jandelgado/gcov2lcov-action@v1.0.0
        with:
          infile: coverage.out
          outfile: coverage.lcov
      - name: Send code coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./coverage.lcov
          flag-name: unit
