---
name: release

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          go mod vendor
      - name: Validate Go releaser config
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: check
      - name: Create GitHub release
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
